server:
  port: 9091
spring:
  application:
    name: order-message-consumer
    rabbitmq:
      host: localhost
      username: guest
      password: guest
      port: 5672
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/macyconsumer
      username: root
      password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
